### ISSUE TITLE
Accessed denied issues when recompiling

### ISSUE THREAD

**Issue by WilliamIX** [ananswam/bioscrape#11]
Sometimes (cause unknown) bioscrape is unable to recompile because access to a specific file (on my machine inference.pyx in C:\Users\wp_ix\Miniconda3\Lib\site-packages\bioscrape, which is not my main bioscrape directory) is denied. This can be fixed by deleting that folder before running python setup.py install.

Suggestion: the setup.py install command should automatically do this.

**Comment by WilliamIX** [comment]
part of the problem, which I figured out from Ayush's suggestions, is that if you have an ipython notebook open that is connected to bioscrape, it can sometimes cause problems when recompiling.

**Comment by ayush9pandey** [comment]
In general, Python package installation suggests that the best practice is to use `pip install .` rather than `python setup.py install`. When `pip install .` is used I usually get a better description of error which says that it couldn't delete the existing copy of installed package and also the output of this command is not as verbose as setup.py install. 

Since, this issue does not arise every time but only intermittently, using `pip install .` is good as you know when your installation failed and so you can uninstall (by deleting the folder) and then reinstall.

**Comment by ayush9pandey** [comment]
It would be desirable to have the installation setup do this automatically. though - so this is something to look into.

**Comment by ananswam** [comment]
I've never had this issue.  Is it possible it's something that is Windows-specific? I re-install while connected in a notebook all the time.

**Comment by WilliamIX** [comment]
Very possible its Window's specific or even python-build specific. I'm generally unclear why setup.py install should have to create directories in my Lib\Site-Packages folder when bioscrape lives somewhere else. Do you know what is going on here?

**Comment by ayush9pandey** [comment]
All Python packages are installed at that location. The bioscrape that
lives somewhere else is your source code that is used to install the
package into Python so that it is recognized universally and can be called
as a package.

**Comment by WilliamIX** [comment]
Looked further - when an active instance of python is using a library (eg you have an ipython notebook and have typed import bioscrape) the folder housing that code is off limits in windows ("in use by an application error"). Not much we can do about this except maybe try to catch the error in the setup.py and give a more useful warning.

**Comment by ayush9pandey** [comment]
Yes, I have observed the same behavior.

**Comment by WilliamIX** [comment]
Don't think there is much we can do here....closing issue.
