### ISSUE TITLE
Volume Constructors Vary

### ISSUE THREAD

**Issue by WilliamIX** [ananswam/bioscrape#13]
What is the right way to create volume objects? Can we clarify the uses of .__init__() vs .setup() vs initialize()?

For example, these two are different (which causes errors in some of anandh's extended examples ipython notebook)

StateDependentVolume:
    def __init__(self): pass
    def setup(self, double average_division_volume, double division_noise, growth_rate, Model m):
    cdef void initialize(self, double *state, double *params, double time, double volume):

StochasticTimeThresholdVolume:
    def __init__(self, double cell_cycle_time, double average_division_volume, double division_noise)
    cdef void initialize(self, double *state, double *params, double time, double volume):

**Comment by ananswam** [comment]
init is the constructor obviously.

setup() is code you run once per volume object to give it the growth rate expression and the model, so it can figure out what rate to grow at. This is only required for the StateDependentVolume because hte other type just grows with no dependence on the state.

initialize() is called at the beginning of each cell cycle. Because the time at which you divide is not a "memoryless" random variable, it is pre-sampled at the beginning of each cell cycle when the division is going to occur (either in time or volume). This could obviously be optimized to be more realistic in future volume models, but something like this will probably always be required to enforce that non-memoryless property, right?

**Comment by ananswam** [comment]
Would be good to rename these functions to have more descriptive names that describe this functionality.

**Comment by WilliamIX** [comment]
This will become a moot point in the new cell lineage package I am developing because volume, division, etc will now be taken care of by Rules and Events (~reactions)
