### ISSUE TITLE
Add a rule type for quasi-steady-state approximation of two-species binding

### ISSUE THREAD

**Issue by sclamons** [ananswam/bioscrape#37]
Example:
A+B<-->A:B
A+A:B = A_tot
B+A:B = B_tot

**Comment by WilliamIX** [comment]
@ayush9pandey this is the simplest case I alluded to in the BioCRNpyler issue thread: https://github.com/BuildACell/BioCRNPyler/issues/56. I think building in this simple rule for two species binding makes sense because we can solve it and it is very common, but how could this procedure be generalized to cases where there is no analytic solution? Worth discussing especially for large networks of things binding and unbinding quickly relative to their creation and destruction (eg transcription factors and other proteins).

**Comment by ayush9pandey** [comment]
As I mentioned in PR #41 this rule type is something that is available in SBML as `AlgebraicRule` (if I understand that correctly). We can implement this rule type in bioscrape as well, possible looking at how other simulators implement the support for simulating models with multiple AlgebraicRules in a general setting?

Probably worth reading -  http://sbml.org/Software/libSBML/docs/formatted/python-api/classlibsbml_1_1_algebraic_rule.html

**Comment by WilliamIX** [comment]
Moved to https://github.com/biocircuits/bioscrape/issues/12
